# System Interface 설정
# 터널 IP 설정
# MSS 사이즈 설정

resource "fortios_system_interface" "us_site_vlan" {
    vdom                    = "root"
    ip                      = "10.92.129.1 255.255.255.0"
    name                    = "us_site_vlan"
    allowaccess             = "ping"
    device_identification   = "enable"
    role                    = "lan"
    interface               = "internal"
    vlanid                  = "92"
    description             = "globalwan by Terraform"
}

resource "fortios_system_interface" "azure-us-1" {
  name                      = fortios_vpnipsec_phase1interface.azure-us-1.name
  vdom                      = "root"
  ip                        = "${lookup(var.azure_vpns[0], "local_ip")}"
  remote_ip                 = "${lookup(var.azure_vpns[0], "bgp_ip")} 255.255.255.255"
  allowaccess               = "ping"
  tcp_mss                   = "1350"
  autogenerated             = "auto"
  status                    = "up"

  depends_on               = [fortios_vpnipsec_phase2interface.azure-us-1]
}

resource "fortios_system_interface" "azure-us-2" {
  name                      = fortios_vpnipsec_phase1interface.azure-us-2.name
  vdom                      = "root"
  ip                        = "${lookup(var.azure_vpns[1], "local_ip")}"
  remote_ip                 = "${lookup(var.azure_vpns[1], "bgp_ip")} 255.255.255.255"
  allowaccess               = "ping"
  tcp_mss                   = "1350"
  autogenerated             = "auto"
  status                    = "up"

  depends_on                = [fortios_vpnipsec_phase2interface.azure-us-2]
}
